trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Twingate
  steps:

  - checkout: self

  - task: Bash@3
    displayName: 'Install Twingate agent'
    inputs:
      targetType: 'inline'
      script: | 
        curl "https://binaries.twingate.com/connector/setup.sh" | sudo TWINGATE_ACCESS_TOKEN="eyJhbGciOiJFUzI1NiIsImtpZCI6Ik1HSW5scTZIWTJLNXNSZDRFdnBVRDBmbVhlNkNwdE9BQmliaHpfbFlTZXMiLCJ0eXAiOiJEQVQifQ.eyJudCI6IkFOIiwiYWlkIjoiMTgxNzY2IiwiZGlkIjoiMTAzOTU0OCIsImp0aSI6Ijg5MzA0Y2ZmLTg4ZjAtNDZhMy05NmFmLTYxYzBlODhkYzgzMCIsImlzcyI6InR3aW5nYXRlIiwiYXVkIjoibmVlcmFqc2hhcm1hMjU5MiIsImV4cCI6MTY5OTQ0NDgyOSwiaWF0IjoxNjk5NDQxMjI5LCJ2ZXIiOiI0IiwidGlkIjoiNjAyMzIiLCJybnciOjE2OTk0NDE1MjksInJuZXRpZCI6Ijc1MzIwIn0.OVmfs69L3OCN7eGzG2wkNNKYYbD2L83xE1FchrD3ju442NVLGlo5Dp158r470ufkg36TnbD44ntQb8jJosTbSA" TWINGATE_REFRESH_TOKEN="xgIEUnx4vQghsgmLD_NlOUSbDOJ0830KQer9aabC7KezEkMgrhaTDJEMV_mZUVGKo64kVQ-tFRKDsTgmcnD9oftYXNndLz_xOGo9zuWjSufZbZa2TDUW5P4YOJjlpuRDq_jLrQ" TWINGATE_NETWORK="neerajsharma2592" bash

  - task: Bash@3
    displayName: 'Add public key to Agent VM'
    inputs:
      targetType: 'inline'
      script: |
        mkdir -p ~/.ssh
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYOAdkF0+N/Q9gWQ3Vq9HI1QpN75hMua8xpJzElFBI4h6IzViRG+lENWA5pq1P2oqHKjYdiLLPo0jjkD7XLlm2g0KmVJ8IcZQnWPJDuVzm3K7SDF5VEWNXyD8RcS4vVQ9y4EMJ0cuq9RrjxEx2Q0I2QXBsFaf2kuy+2YbrMEDHWgUwwwbx6v3AYF6ziJngpKhh2G7A6yCyCquaxMjnFJyRXcPvvAyQJ52mLy+UY7xCnW1UCtgulAirH/andefq6Aw2kHB2zaUAT5tkXNEd9P7aaURbqqBYrvmtuFHPD/0JXdK0/Ck+TuXfU20OjthfmkWNwA8npXj86zL9eLUd/mabrf/B1xI7Nhb/Jw/8uFJE4FiHjoxRVP8PxG80BQINWKJc+U/LxRC/iuUh4dTUxqZlszI1e1ItMs4tA8KIlkmajT4LBKrG/AohxDszHRdY35Y24tIPps9H0gaSfjxmJD9CzdMN0zx/y9ruxPj+i6ZG+RD2n5SWdvJM6GOf10lAfAU= neerajsharma@Neerajs-MacBook-Air.local
" >> ~/.ssh/authorized_keys

  - task: Bash@3
    displayName: 'Show agent IP address'
    inputs:
      targetType: 'inline'
      script: |
        export ETH0_IP=$(ip addr show eth0 | grep "inet\\b" | awk '{print $2}' | cut -d/ -f1) 
        echo "##[section]CONNECT WITH: ssh vsts@$ETH0_IP"
        sleep 1h
